application:
  runtimeManifest:
    packages:
      ac_kk_integration:
        license: Apache-2.0
        actions:
#          product-kk-to-acstg:
#            function: actions/kk2ac/product_kk_to_acstg.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 4096
#          product-acstg-to-ac:
#            function: actions/kk2ac/product_acstg_to_ac.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 4096
#          price-kk-to-acstg:
#            function: actions/kk2ac/price_kk_to_acstg.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 4096
#          price-acstg-to-ac:
#            function: actions/kk2ac/price_acstg_to_ac.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 4096
#          inventory-kk-to-acstg:
#            function: actions/kk2ac/inventory_kk_to_acstg.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 409
#          inventory-acstg-to-ac:
#            function: actions/kk2ac/inventory_acstg_to_ac.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 4096
#          company-kk-to-acstg:
#            function: actions/kk2ac/company_kk_to_acstg.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 409
          company-acstg-to-ac:
            function: actions/kk2ac/company_acstg_to_ac.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
              KINETIC_API_URL: $KINETIC_API_URL
              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
              KINETIC_USERNAME: $KINETIC_USERNAME
              KINETIC_PASSWORD: $KINETIC_PASSWORD
              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
              KINETIC_LICENSE: $KINETIC_LICENSE
              KINETIC_COMPANY: $KINETIC_COMPANY
              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
            annotations:
              require-adobe-auth: false
              final: true
            limits:
              timeout: 1800000
              memory: 409
#          contact-kk-to-acstg:
#            function: actions/kk2ac/contact_kk_to_acstg.js
#            web: 'yes'
#            runtime: nodejs:18
#            inputs:
#              LOG_LEVEL: debug
#              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
#              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
#              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
#              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
#              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
#              KINETIC_API_URL: $KINETIC_API_URL
#              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
#              KINETIC_USERNAME: $KINETIC_USERNAME
#              KINETIC_PASSWORD: $KINETIC_PASSWORD
#              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
#              KINETIC_LICENSE: $KINETIC_LICENSE
#              KINETIC_COMPANY: $KINETIC_COMPANY
#              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
#              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
#            annotations:
#              require-adobe-auth: false
#              final: true
#            limits:
#              timeout: 1800000
#              memory: 409
          contact-acstg-to-ac:
            function: actions/kk2ac/contact_acstg_to_ac.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              COMMERCE_BASE_URL: $COMMERCE_BASE_URL
              COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
              COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
              COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
              COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
              KINETIC_API_URL: $KINETIC_API_URL
              KINETIC_API_HOST_PORT: $KINETIC_API_HOST_PORT
              KINETIC_USERNAME: $KINETIC_USERNAME
              KINETIC_PASSWORD: $KINETIC_PASSWORD
              KINETIC_X_API_KEY: $KINETIC_X_API_KEY
              KINETIC_LICENSE: $KINETIC_LICENSE
              KINETIC_COMPANY: $KINETIC_COMPANY
              KINETIC_CLIENT_CERT: $KINETIC_CLIENT_CERT
              KINETIC_CLIENT_KEY: $KINETIC_CLIENT_KEY
            annotations:
              require-adobe-auth: false
              final: true
            limits:
              timeout: 1800000
              memory: 409
#      starter-kit:
#        license: Apache-2.0
#        actions:
#          # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
#          info:
#            function: actions/starter-kit-info/index.js
#            web: 'yes'
#            runtime: nodejs:20
#            inputs:
#              LOG_LEVEL: debug
#            annotations:
#              require-adobe-auth: true
#              final: true
      #  ingestion:
      #    license: Apache-2.0
      #    actions:
      #      $include: ./actions/ingestion/actions.config.yaml
#      webhook:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/webhook/actions.config.yaml
#      product-commerce:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/product/commerce/actions.config.yaml
#      product-backoffice:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/product/external/actions.config.yaml
#      customer-commerce:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/customer/commerce/actions.config.yaml
#      customer-backoffice:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/customer/external/actions.config.yaml
#      order-commerce:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/order/commerce/actions.config.yaml
#      order-backoffice:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/order/external/actions.config.yaml
#      stock-commerce:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/stock/commerce/actions.config.yaml
#      stock-backoffice:
#        license: Apache-2.0
#        actions:
#          $include: ./actions/stock/external/actions.config.yaml
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
