module.exports = Object.freeze({
    PRODUCT_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_Products/Data",
    PRODUCT_PRICE_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_ListPrice/Data",
    PRODUCT_TIRE_PRICE_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_ListPriceQtyBreaks/Data",
    PRODUCT_INVENTORY_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_ProductInventory/Data",
    COMPANY_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_Customers/Data",
    CONTACT_STAGING_BAQ_URI: "api/v2/odata/RB/BaqSvc/RBk22_Web_Contacts/Data",
    STAGING_TABLE_UPD_FUNC_URI: "api/v2/efx/RB/WebIntegrations/RBk22-StagingTableProcessed",

});

'{"record_id":386938,"staging_time_stamp":"2024-07-19T08:17:00.727-04:00","part_number":"TR280124","description":"2803-H Horizontal Live End Pulley","sales_uom":"Each","web_active":true,"discontinued":false,"base_sku":"","variant_attribute_nominal_color":"Black","variant_attribute_size":"","bundle_base_sku_list":"","sellable_site_list":"MfgSys~RBW","drop_ship_part":false,"web_lead_days":0,"infinite_inventory":false,"closeout_price":0,"closeout_original_price":0,"promo_min_qty":0,"promo_percent_off":0,"promo_start_date":null,"promo_end_date":null,"net_weight":60,"net_weight_uom":"Ounce","gross_weight":3.75,"gross_weight_uom":"Pound","net_volume":0,"net_volume_uom":"","part_length":7.5,"part_width":6,"part_height":4,"part_length_width_height_um":"Inch","thickness":0,"thickness_um":"","diameter_inside":0,"diameter_outside":0,"diameter_um":"","roll_length":0,"roll_length_uom":"","shipping_group":"Dimensional","packing_rule":"Dimensional_Pk","is_malleable":false,"malleable_max_qty":0,"ship_length":7.5,"ship_width":6,"ship_height":4,"malleable_length":0,"malleable_width":0,"malleable_height":0,"length_width_height_um":"Inch","freight_class":"100","drop_ship_origin_code":"","country_of_origin":"United States","hs_commodity_code":"8302.49.7500","commercial_brand":"ADC","generic_color":"Black","product_type":"Pulleys","component_type":"","material_composition":"Steel","construction":"","nominal_weight":"","gsm_weight":0,"printable":false,"finish":"","opacity":"","sheen":"","hex_color_code":"","pantone_number":"","gain_front_projection":0,"gain_rear_projection":0,"acoustic_nrc":0,"acoustic_saa":0,"coverage":"","horse_power":"","voltage":"","wattage":"","speed":"","capacity":"","load_rated":false,"features1_label":"","features1":"","features2_label":"","features2":"","type":"Not Applicable","fiber_content":"","ca_registration_number":"","fr_test_nfpa701":false,"fr_test_ca_title19":false,"fr_test_cans109":false,"fr_test_astme84":false,"fr_test_en13773":false,"fr_test_german_b1":false,"fr_test_french_m1":false,"fr_test_en13501":false,"fr_test_british5867":false,"fr_test_imo":false,"fr_test_bfd":false,"fr_test_nfpa253":false,"fr_test_astmd2859":false,"exported_to_web":false,"export_time_stamp":null,"row_ident":"000000b4-0000-0000-0000-000000000000","sku":"TR280124","name":"2803-H Horizontal Live End Pulley","kinetic_description":"2803-H Horizontal Live End Pulley","weight":3.75,"status":true}'